services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\ParserBundle\:
        resource: '../../../../ParserBundle'
        exclude:
            - './ParserBundle/DependencyInjection/'
            - './ParserBundle/Entity/'
            - './ParserBundle/Kernel.php'

    App\ParserBundle\Presentation\Web\Controller\: # assuming you have namespace like that
        resource: '../../../Presentation/Web/Controller'
        tags: [ 'controller.service_arguments' ]

    App\ParserBundle\Infrastructure\FileReader\ExtensionAwareFileReader:
        calls:
            -   addReader: [ 'zip', '@App\ParserBundle\Infrastructure\FileReader\ZipFileReader' ],
            -   addReader: [ 'json', '@App\ParserBundle\Infrastructure\FileReader\JsonFileReader' ]

    App\ParserBundle\Infrastructure\FileReader\FileReaderInterface: '@App\ParserBundle\Infrastructure\FileReader\ExtensionAwareFileReader'

    App\ParserBundle\Infrastructure\Shared\Filesystem\LocalFilesystem:
        - '%kernel.project_dir%/upload/'


    App\ParserBundle\Application\AuthenticateShoprenterWorker\AuthenticateShoprenterWorkerHandler:
            tags:
                -
                    name: messenger.message_handler
                    bus: query.bus
                    handles: App\ParserBundle\Application\AuthenticateShoprenterWorker\AuthenticateShoprenterWorkerQuery

    App\ParserBundle\Application\GetImagesFromFile\GetImagesFromFileHandler:
        tags:
            -   name: messenger.message_handler
                bus: query.bus
                handles: App\ParserBundle\Application\GetImagesFromFile\GetImagesFromFileQuery

    App\ParserBundle\Application\GetShoprenterWorkerById\GetShoprenterWorkerByIdHandler:
        tags:
            -   name: messenger.message_handler
                bus: query.bus
                handles: App\ParserBundle\Application\GetShoprenterWorkerById\GetShoprenterWorkerByIdQuery